global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']
